# Generated by Django 3.1.7 on 2021-03-10 11:12

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='uploadTime',
            field=models.DateTimeField(validators=[files.models.validate_date_gte_now]),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='uploadTime',
            field=models.DateTimeField(validators=[files.models.validate_date_gte_now]),
        ),
        migrations.AlterField(
            model_name='song',
            name='uploadTime',
            field=models.DateTimeField(validators=[files.models.validate_date_gte_now]),
        ),
    ]
