# Generated by Django 3.1.7 on 2021-03-09 09:32

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_podcast_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='participants',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), blank=True, max_length=110, null=True, size=10),
        ),
    ]
